// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // The CLI (db push, generate, seed) needs a direct/session connection —
    // Supabase's transaction-mode pooler (used by DATABASE_URL at runtime,
    // see src/lib/prisma.ts) doesn't reliably support schema-altering DDL.
    url: process.env["DIRECT_URL"] || process.env["DATABASE_URL"],
  },
});
