export type AdminBooking = {
  id: string;
  reference: string;
  clientId: string;
  serviceId: string;
  requestedDate: string;
  requestedTime: string;
  proposedDate: string | null;
  proposedTime: string | null;
  proposalMessage: string | null;
  proposalExpiresAt: string | null;
  status: string;
  depositStatus: string;
  depositMethod: string | null;
  depositRecordedAt: string | null;
  nailArtCount: number | null;
  serviceSubtotal: number;
  addOnsTotal: number;
  estimatedTotal: number;
  depositAmount: number;
  remainingBalance: number;
  clientName: string;
  clientEmail: string;
  clientPhone: string;
  designNotes: string;
  inspirationImageUrl: string | null;
  cancellationFeeStatus: string;
  cancellationFeeAmount: number | null;
  cancellationReason: string | null;
  adminNotes: string;
  createdAt: string;
  updatedAt: string;
  service: { id: string; name: string; durationMinutes: number };
  client: { id: string; name: string; email: string; phone: string; restricted: boolean; restrictionReason: string | null };
  addOns: { id: string; nailCount: number | null; calculatedPrice: number; service: { id: string; name: string } }[];
  policyAcceptance: { id: string; policyVersion: string; acceptedAt: string; consentText: string } | null;
  statusHistory: { id: string; fromStatus: string | null; toStatus: string; changedBy: string; note: string | null; createdAt: string }[];
};
